---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no   # runs the "setup" module on remote hosts

  # these variables are used to build templates
  vars_files:
    - vars/challangehosts.yml
    - vars/challangeips.yml

  tasks:
    - name: Create host and IP list
      template:
        src: templates/chall.j2    # name of the template on ansible controller
        dest: ~/wedschall.cfg              # name of the completed file to be placed on the target system

        #    - name: Configure mission orders
        #      template:
        #        src: templates/mission-orders.txt.j2    # name of the template on ansible controller
        #        dest: ~/mission-orders.txt              # name of the completed file to be placed on the target system

